### PR TITLE
add information about x86 emulation

### PR DESCRIPTION
**Pull request by tardyp**

### CODE REVIEW

**Comment by simnalamburt** [comment]
Hi! I don’t actually get a meaning of this PR. Are you sure about that installing yet another qemu-static *inside* the qemu let us run the amd64 docker images?

**Comment by tardyp** [comment]
Ahah! Indeed that sounds pretty silly. 

We run qemu the emulator inside qemu the hypervisor. From my understanding, this is also what is doing docker-for-mac, except they use their own hypervisor instead of qemu, but they do use qemu-static.

It does work and is super slow (about 10 time slower for a gcc compilation).

Do you think it would be faster to use an x86 VM as the podman machine instead?
Maybe the qemu JIT cache can stay warmer, but that means the kernel has to be emulated.

**Comment by simnalamburt** [comment]
I’m currently working on other method that is to let podman run
qemu-system-x86_64 with tcg(tiny codegen) accel, which should be much
faster than double qemu. :)

2021년 9월 7일 (화) 03:57, Pierre Tardy ***@***.***>님이 작성:

**Comment by tardyp** [comment]
cool! let me know if I can help.

**Comment by simnalamburt** [comment]
I'll close this PR and update the progress at https://github.com/simnalamburt/podman/issues/1!

**Pull request closed without merging**
